import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import '../providers/app_provider.dart';
import '../services/supabase_service.dart';
import '../models/grocery_usage_model.dart';
import '../models/report_model.dart';

class TeacherDashboard extends StatefulWidget {
  const TeacherDashboard({super.key});

  @override
  State<TeacherDashboard> createState() => _TeacherDashboardState();
}

class _TeacherDashboardState extends State<TeacherDashboard> {
  int _selectedIndex = 0;
  final _groceryFormKey = GlobalKey<FormState>();
  final _reportFormKey = GlobalKey<FormState>();
  
  final _groceryNameController = TextEditingController();
  final _quantityController = TextEditingController();
  DateTime _selectedDate = DateTime.now();
  DateTime? _fromDate;
  DateTime? _toDate;
  
  List<GroceryUsageModel> _groceryUsageList = [];
  List<ReportModel> _reportsList = [];
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _loadGroceryUsage();
    _loadReports();
  }

  @override
  void dispose() {
    _groceryNameController.dispose();
    _quantityController.dispose();
    super.dispose();
  }

  Future<void> _loadGroceryUsage() async {
    final user = Provider.of<AppProvider>(context, listen: false).currentUser;
    if (user != null) {
      setState(() => _isLoading = true);
      final usage = await SupabaseService.getGroceryUsageByDateRange(
        user.id,
        DateTime.now().subtract(const Duration(days: 30)),
        DateTime.now(),
      );
      setState(() {
        _groceryUsageList = usage;
        _isLoading = false;
      });
    }
  }

  Future<void> _loadReports() async {
    final user = Provider.of<AppProvider>(context, listen: false).currentUser;
    if (user != null) {
      final reports = await SupabaseService.getReportsByTeacher(user.id);
      setState(() => _reportsList = reports);
    }
  }

  Future<void> _selectDate(BuildContext context) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2020),
      lastDate: DateTime.now(),
    );
    if (picked != null) {
      setState(() => _selectedDate = picked);
    }
  }

  Future<void> _selectFromDate(BuildContext context) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _fromDate ?? DateTime.now(),
      firstDate: DateTime(2020),
      lastDate: DateTime.now(),
    );
    if (picked != null) {
      setState(() => _fromDate = picked);
    }
  }

  Future<void> _selectToDate(BuildContext context) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _toDate ?? DateTime.now(),
      firstDate: _fromDate ?? DateTime(2020),
      lastDate: DateTime.now(),
    );
    if (picked != null) {
      setState(() => _toDate = picked);
    }
  }

  Future<void> _addGroceryUsage() async {
    if (_groceryFormKey.currentState!.validate()) {
      final user = Provider.of<AppProvider>(context, listen: false).currentUser;
      if (user != null) {
        final usage = GroceryUsageModel(
          id: '', // Will be generated by Supabase (UUID)
          teacherId: user.id,
          date: _selectedDate,
          groceryName: _groceryNameController.text.trim(),
          quantity: double.parse(_quantityController.text.trim()),
        );

        final success = await SupabaseService.addGroceryUsage(usage);
        if (success && mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('గ్రోసరీ ఉపయోగం జతచేయబడింది'),
              backgroundColor: Colors.green,
            ),
          );
          _groceryNameController.clear();
          _quantityController.clear();
          _loadGroceryUsage();
        } else if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('దోషం సంభవించింది'),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    }
  }

  Future<void> _generateReport() async {
    if (_reportFormKey.currentState!.validate()) {
      if (_fromDate == null || _toDate == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('దయచేసి తేదీలను ఎంచుకోండి'),
            backgroundColor: Colors.red,
          ),
        );
        return;
      }

      final user = Provider.of<AppProvider>(context, listen: false).currentUser;
      if (user != null) {
        setState(() => _isLoading = true);

        final usageList = await SupabaseService.getGroceryUsageByDateRange(
          user.id,
          _fromDate!,
          _toDate!,
        );

        // Aggregate grocery quantities
        final Map<String, double> aggregated = {};
        final Map<String, String> units = {};

        for (var usage in usageList) {
          if (aggregated.containsKey(usage.groceryName)) {
            aggregated[usage.groceryName] =
                aggregated[usage.groceryName]! + usage.quantity;
          } else {
            aggregated[usage.groceryName] = usage.quantity;
            units[usage.groceryName] = usage.unit;
          }
        }

        final reportItems = aggregated.entries.map((entry) {
          return GroceryReportItem(
            groceryName: entry.key,
            totalQuantity: entry.value,
            unit: units[entry.key] ?? 'kg',
          );
        }).toList();

        final report = ReportModel(
          id: '', // Will be generated by Supabase (UUID)
          teacherId: user.id,
          teacherName: user.name,
          fromDate: _fromDate!,
          toDate: _toDate!,
          groceryItems: reportItems,
          submittedAt: DateTime.now(),
        );

        final success = await SupabaseService.submitReport(report);
        setState(() => _isLoading = false);

        if (success && mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('రిపోర్ట్ సమర్పించబడింది'),
              backgroundColor: Colors.green,
            ),
          );
          _fromDate = null;
          _toDate = null;
          _loadReports();
        } else if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('దోషం సంభవించింది'),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final user = Provider.of<AppProvider>(context).currentUser;

    return Scaffold(
      appBar: AppBar(
        title: const Text('టీచర్ డాష్బోర్డ్'),
        backgroundColor: Colors.blue.shade700,
        foregroundColor: Colors.white,
        actions: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Center(
              child: Text(
                user?.name ?? '',
                style: const TextStyle(fontWeight: FontWeight.bold),
              ),
            ),
          ),
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () {
              Provider.of<AppProvider>(context, listen: false).logout();
              Navigator.of(context).pop();
            },
          ),
        ],
      ),
      body: Row(
        children: [
          NavigationRail(
            selectedIndex: _selectedIndex,
            onDestinationSelected: (index) {
              setState(() => _selectedIndex = index);
            },
            labelType: NavigationRailLabelType.all,
            destinations: const [
              NavigationRailDestination(
                icon: Icon(Icons.add_shopping_cart),
                label: Text('గ్రోసరీ జోడించండి'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.description),
                label: Text('రిపోర్ట్ జనరేట్ చేయండి'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.history),
                label: Text('రిపోర్ట్ చరిత్ర'),
              ),
            ],
          ),
          const VerticalDivider(thickness: 1, width: 1),
          Expanded(
            child: _isLoading
                ? const Center(child: CircularProgressIndicator())
                : IndexedStack(
                    index: _selectedIndex,
                    children: [
                      _buildGroceryEntryForm(),
                      _buildReportGenerationForm(),
                      _buildReportsHistory(),
                    ],
                  ),
          ),
        ],
      ),
    );
  }

  Widget _buildGroceryEntryForm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Card(
        elevation: 4,
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _groceryFormKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  'గ్రోసరీ ఉపయోగం జోడించండి',
                  style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                ),
                const SizedBox(height: 24),
                InkWell(
                  onTap: () => _selectDate(context),
                  child: InputDecorator(
                    decoration: InputDecoration(
                      labelText: 'తేదీ',
                      prefixIcon: const Icon(Icons.calendar_today),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: Text(
                      DateFormat('yyyy-MM-dd').format(_selectedDate),
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _groceryNameController,
                  decoration: InputDecoration(
                    labelText: 'గ్రోసరీ పేరు',
                    prefixIcon: const Icon(Icons.shopping_bag),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'దయచేసి గ్రోసరీ పేరు నమోదు చేయండి';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _quantityController,
                  decoration: InputDecoration(
                    labelText: 'పరిమాణం (kg)',
                    prefixIcon: const Icon(Icons.scale),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  keyboardType: TextInputType.number,
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'దయచేసి పరిమాణం నమోదు చేయండి';
                    }
                    if (double.tryParse(value) == null) {
                      return 'దయచేసి చెల్లుబాటు అయ్యే సంఖ్యను నమోదు చేయండి';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: _addGroceryUsage,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue.shade700,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text(
                    'జోడించండి',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                ),
                const SizedBox(height: 32),
                Text(
                  'ఇటీవలి ఉపయోగం',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                ),
                const SizedBox(height: 16),
                _groceryUsageList.isEmpty
                    ? const Text('ఇంకా ఎటువంటి ఉపయోగం లేదు')
                    : ListView.builder(
                        shrinkWrap: true,
                        physics: const NeverScrollableScrollPhysics(),
                        itemCount: _groceryUsageList.length,
                        itemBuilder: (context, index) {
                          final usage = _groceryUsageList[index];
                          return Card(
                            margin: const EdgeInsets.only(bottom: 8),
                            child: ListTile(
                              title: Text(usage.groceryName),
                              subtitle: Text(
                                DateFormat('yyyy-MM-dd').format(usage.date),
                              ),
                              trailing: Text(
                                '${usage.quantity} ${usage.unit}',
                                style: const TextStyle(
                                  fontWeight: FontWeight.bold,
                                  fontSize: 16,
                                ),
                              ),
                            ),
                          );
                        },
                      ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildReportGenerationForm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Card(
        elevation: 4,
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _reportFormKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  'రిపోర్ట్ జనరేట్ చేయండి',
                  style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                ),
                const SizedBox(height: 24),
                InkWell(
                  onTap: () => _selectFromDate(context),
                  child: InputDecorator(
                    decoration: InputDecoration(
                      labelText: 'నుండి తేదీ',
                      prefixIcon: const Icon(Icons.calendar_today),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: Text(
                      _fromDate == null
                          ? 'తేదీని ఎంచుకోండి'
                          : DateFormat('yyyy-MM-dd').format(_fromDate!),
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                InkWell(
                  onTap: () => _selectToDate(context),
                  child: InputDecorator(
                    decoration: InputDecoration(
                      labelText: 'వరకు తేదీ',
                      prefixIcon: const Icon(Icons.calendar_today),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: Text(
                      _toDate == null
                          ? 'తేదీని ఎంచుకోండి'
                          : DateFormat('yyyy-MM-dd').format(_toDate!),
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: _generateReport,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.green.shade700,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text(
                    'రిపోర్ట్ జనరేట్ చేసి సమర్పించండి',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildReportsHistory() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Text(
            'రిపోర్ట్ చరిత్ర',
            style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 24),
          _reportsList.isEmpty
              ? const Center(
                  child: Text('ఇంకా ఎటువంటి రిపోర్ట్ లేదు'),
                )
              : ListView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: _reportsList.length,
                  itemBuilder: (context, index) {
                    final report = _reportsList[index];
                    return Card(
                      margin: const EdgeInsets.only(bottom: 16),
                      elevation: 4,
                      child: ExpansionTile(
                        title: Text(
                          '${DateFormat('yyyy-MM-dd').format(report.fromDate)} - ${DateFormat('yyyy-MM-dd').format(report.toDate)}',
                        ),
                        subtitle: Text(
                          'సమర్పించిన తేదీ: ${DateFormat('yyyy-MM-dd HH:mm').format(report.submittedAt)}',
                        ),
                        children: [
                          Padding(
                            padding: const EdgeInsets.all(16.0),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.stretch,
                              children: [
                                const Text(
                                  'గ్రోసరీ వివరాలు:',
                                  style: TextStyle(
                                    fontWeight: FontWeight.bold,
                                    fontSize: 16,
                                  ),
                                ),
                                const SizedBox(height: 8),
                                ...report.groceryItems.map((item) {
                                  return ListTile(
                                    title: Text(item.groceryName),
                                    trailing: Text(
                                      '${item.totalQuantity} ${item.unit}',
                                      style: const TextStyle(
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  );
                                }),
                              ],
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                ),
        ],
      ),
    );
  }
}

